# Generated by Django 4.1.1 on 2022-09-15 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='fecha_creacio',
            new_name='fecha_creacion',
        ),
    ]
