# Generated by Django 4.1.1 on 2022-09-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_rename_fecha_creacio_post_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contenido',
            field=models.TextField(default=False, max_length=2000),
        ),
    ]
