# Generated by Django 4.1.1 on 2022-09-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_post_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
